// Semua string UI Bahasa Melayu — TIADA string hardcoded dalam component.
// Rujuk PRD v2.0 Seksyen 17 (AI coding rules) #7.

export const ms = {
  sistem: {
    nama: "Sistem Pengurusan BLPP KEMAS",
    namaPendek: "xBLPP",
  },
  nav: {
    aset: "Aset & Premis",
    latihan: "Latihan",
    admin: "Pentadbiran",
  },
  admin: {
    pengguna: {
      tajuk: "Pengurusan Pengguna",
      senarai: "Senarai Pengguna",
      ciptaPengguna: "Cipta Pengguna",
      labelNama: "Nama",
      labelEmel: "E-mel",
      labelTelefon: "Telefon",
      labelJawatan: "Jawatan",
      labelRole: "Peranan",
      labelNegeri: "Negeri",
      labelDaerah: "Daerah",
      labelPremis: "Premis",
      tiadaBerkaitan: "— Tiada berkaitan —",
      simpan: "Cipta",
      resetPassword: "Reset Password",
      resetPasswordKonfirmasi: "Reset password pengguna ini?",
      ralatEmelWujud: "E-mel ini sudah didaftarkan.",
      tempPasswordTajuk: "Password sementara (paparan SEKALI sahaja)",
      tempPasswordAmaran:
        "Salin dan hantar kepada pengguna sekarang (WhatsApp/telefon) — tidak akan dipaparkan semula. Pengguna WAJIB tukar password semasa log masuk pertama.",
      lajurNama: "Nama",
      lajurEmel: "E-mel",
      lajurRole: "Peranan",
      lajurStatus: "Status",
      lajurTindakan: "Tindakan",
    },
  },
  auth: {
    login: "Log Masuk",
    labelId: "E-mel",
    labelKataLaluan: "Kata Laluan",
    labelKataLaluanBaharu: "Kata Laluan Baharu",
    labelSahkanKataLaluan: "Sahkan Kata Laluan Baharu",
    lupaKataLaluan: "Lupa Kata Laluan?",
    resetKataLaluan: "Set Semula Kata Laluan",
    resetKataLaluanKeterangan:
      "Kata laluan anda perlu ditukar sebelum meneruskan.",
    resetKataLaluanButang: "Kemaskini Kata Laluan",
    resetKataLaluanBerjaya: "Kata laluan berjaya dikemaskini.",
    sedangLog: "Sedang log masuk...",
    ralat: {
      invalid_credentials: "E-mel atau kata laluan salah.",
      locked: "Akaun dikunci sementara akibat terlalu banyak percubaan gagal. Sila cuba semula selepas 15 minit.",
      inactive: "Akaun anda tidak aktif. Hubungi admin.",
      kataLaluanSemasaSalah: "Kata laluan semasa salah.",
      kataLaluanTidakSepadan: "Kata laluan baharu tidak sepadan.",
      kataLaluanTerlaluPendek: "Kata laluan mesti sekurang-kurangnya 10 aksara.",
    },
  },
  aset: {
    premis: "Premis",
    tempahan: "Tempahan",
    penyelenggaraan: "Penyelenggaraan",
    tambahPremis: "Tambah Premis",
    editPremis: "Kemaskini Premis",
    tambahFasiliti: "Tambah Fasiliti",
    editFasiliti: "Kemaskini Fasiliti",
    senaraiFasiliti: "Fasiliti",
    labelNama: "Nama",
    labelJenis: "Jenis",
    labelAlamat: "Alamat",
    labelNegeri: "Negeri",
    labelDaerah: "Daerah",
    labelGoogleMaps: "Pautan Google Maps",
    labelPic: "PIC Premis",
    labelStatus: "Status",
    labelKapasiti: "Kapasiti",
    picTiadaDipilih: "— Tiada —",
    simpan: "Simpan",
    kemaskini: "Kemaskini",
    berjayaDicipta: "Berjaya dicipta.",
    berjayaDikemaskini: "Berjaya dikemaskini.",
    jenisVenue: {
      akademi: "Akademi Latihan KEMAS",
      ilk: "Institut Latihan KEMAS",
      plk: "Pusat Latihan KEMAS",
      pkm: "Pusat Kegiatan Masyarakat",
    },
    statusVenue: {
      aktif: "Aktif",
      tutup: "Tutup",
    },
    jenisFasiliti: {
      dewan: "Dewan",
      bilik_seminar: "Bilik Seminar",
      makmal: "Makmal",
      asrama: "Asrama",
      lain: "Lain-lain",
    },
    statusFasiliti: {
      aktif: "Aktif",
      maintenance: "Penyelenggaraan",
      tutup: "Tutup",
    },
    labelMaintenanceUntil: "Penyelenggaraan Sehingga",
    notaMaintenanceUntil:
      "Isi hanya jika status Penyelenggaraan. Kosongkan jika tiada tarikh tamat dijangka. Tempahan sedia ada yang bertindih akan ditanda \"Perlu Dipindah\" dan pemohon dimaklumkan.",
    notifikasi: {
      picDilantikTajuk: "Anda dilantik sebagai PIC premis",
      picDilantikBadan: (venue: string) => `Anda kini PIC bagi premis ${venue}. Anda akan menerima tempahan untuk kelulusan peringkat pertama.`,
    },
    dashboard: {
      tajuk: "Papan Pemuka",
      jumlahPremis: "Jumlah Premis",
      jumlahFasiliti: "Jumlah Fasiliti",
      kadarPenggunaan: "Kadar Penggunaan Fasiliti",
      kadarPenggunaanNota: (guna: number, jumlah: number) => `${guna} daripada ${jumlah} fasiliti ada tempahan aktif/akan datang`,
      tempahanMenungguKelulusan: "Tempahan Menunggu Kelulusan",
      tiadaMenungguKelulusan: "Tiada tempahan menunggu kelulusan.",
      slaLagi: (hari: number) => `${hari} hari lagi`,
      slaTertunggak: (hari: number) => `Tertunggak ${hari} hari`,
      slaHariIni: "Tamat tempoh hari ini",
      statusPenyelenggaraan: "Fasiliti Dalam Penyelenggaraan",
      tiadaPenyelenggaraan: "Tiada fasiliti dalam penyelenggaraan.",
      aktivitiTerkini: "Aktiviti Terkini",
      tiadaAktiviti: "Tiada aktiviti direkodkan.",
      pautanCepat: "Pautan Pantas",
    },
  },
  tempahan: {
    tajuk: "Tempahan",
    tempahBaharu: "Tempah Fasiliti",
    labelJenisTempahan: "Jenis Tempahan",
    labelFasiliti: "Fasiliti",
    labelTujuan: "Tujuan",
    labelAnggaranPeserta: "Anggaran Bilangan Peserta",
    labelMasaMula: "Masa Mula",
    labelMasaTamat: "Masa Tamat",
    labelStatus: "Status",
    maklumatPenyewa: "Maklumat Penyewa",
    labelPenyewaNama: "Nama Penyewa",
    labelPenyewaOrganisasi: "Organisasi",
    labelPenyewaTelefon: "Telefon Penyewa",
    labelPenyewaEmel: "E-mel Penyewa",
    notaKadarSewaan: "Kadar sewaan akan ditetapkan kemudian — belum berkuat kuasa buat masa ini.",
    simpan: "Hantar Tempahan",
    tiadaTempahan: "Tiada tempahan lagi.",
    amaranKelulusanNegeri:
      "Tempahan lebih 12 bulan ke hadapan memerlukan perhatian tambahan semasa semakan HQ.",
    amaranDwiKelulusan: "Setiap tempahan perlu kelulusan PIC premis, kemudian kelulusan HQ.",
    tempahBerulang: "Tempah Berulang",
    labelCorakUlangan: "Corak Ulangan",
    labelBilanganUlangan: "Bilangan Ulangan",
    notaKejadianPertama: "Tarikh/masa di atas ialah kejadian PERTAMA — kejadian seterusnya dijana automatik.",
    simpanBerulang: "Hantar Siri Tempahan",
    ringkasanBerulang: "Ringkasan Siri Tempahan",
    ringkasanBerjaya: (created: number, total: number) => `${created} daripada ${total} kejadian berjaya ditempah.`,
    ringkasanGagalTajuk: "Kejadian yang gagal:",
    lihatSenarai: "Lihat Senarai Tempahan",
    tempahLagiSatu: "Tempah Lagi",
    lulus: "Lulus",
    tolak: "Tolak",
    labelSebabTolak: "Sebab Penolakan",
    hantarPenolakan: "Hantar Penolakan",
    labelPicLulus: "Kelulusan PIC",
    labelHqLulus: "Kelulusan HQ",
    labelPemohon: "Pemohon",
    belumBertindak: "Belum bertindak",
    ditolakOleh: "Ditolak Oleh",
    slaDeadline: "Tarikh Akhir SLA",
    tindakanPic: "Tindakan Kelulusan (Peringkat PIC)",
    tindakanHq: "Tindakan Kelulusan (Peringkat HQ)",
    batalkanTempahan: "Batalkan Tempahan",
    labelSebabBatal: "Sebab Pembatalan",
    labelSebabBatalOpsyenal: "Sebab Pembatalan (opsyenal)",
    notaSebabBatalWajib: "Pembatalan kurang 3 hari sebelum tarikh guna memerlukan sebab.",
    hantarPembatalan: "Sahkan Pembatalan",
    dibatalkanOleh: "Dibatalkan Oleh",
    ralat: {
      tarikhLampau: "Tempahan tarikh lampau tidak dibenarkan.",
      konflik: "Fasiliti ini sudah ditempah pada masa yang bertindih. Sila pilih masa/fasiliti lain.",
      statusBukanMenunggu: "Tempahan ini sudah diproses (bukan lagi menunggu kelulusan).",
      sebabTolakWajib: "Sebab penolakan wajib diisi.",
      tidakBolehBatal: "Tempahan ini tidak boleh dibatalkan (sudah selesai/dibatalkan/tarikh lepas).",
      sebabBatalWajib: "Pembatalan kurang 3 hari sebelum tarikh guna memerlukan sebab.",
    },
    notifikasi: {
      picBaharuTajuk: "Tempahan baharu menunggu kelulusan anda",
      picBaharuBadan: (fasiliti: string, venue: string) =>
        `Tempahan baharu untuk ${fasiliti} (${venue}) menunggu kelulusan PIC anda.`,
      picLulusTajuk: "Tempahan anda diluluskan PIC",
      picLulusBadan: (fasiliti: string) => `Tempahan ${fasiliti} anda diluluskan PIC, kini menunggu kelulusan HQ.`,
      hqMenungguTajuk: "Tempahan menunggu kelulusan HQ",
      hqMenungguBadan: (fasiliti: string, venue: string) =>
        `Tempahan ${fasiliti} (${venue}) telah diluluskan PIC, menunggu kelulusan HQ.`,
      diluluskanTajuk: "Tempahan diluluskan penuh",
      diluluskanBadan: (fasiliti: string) => `Tempahan ${fasiliti} telah diluluskan sepenuhnya (PIC + HQ).`,
      ditolakTajuk: "Tempahan ditolak",
      ditolakBadan: (fasiliti: string, sebab: string) => `Tempahan ${fasiliti} ditolak. Sebab: ${sebab}`,
      perluPindahTajuk: "Tempahan anda perlu dipindah (penyelenggaraan)",
      perluPindahBadan: (fasiliti: string, venue: string) =>
        `${fasiliti} (${venue}) akan menjalani penyelenggaraan pada tarikh tempahan anda. Sila hubungi PIC premis untuk pindah tarikh/fasiliti.`,
      dibatalkanSlotTajuk: "Slot fasiliti dibebaskan (tempahan dibatalkan)",
      dibatalkanSlotBadan: (fasiliti: string, venue: string) => `Tempahan untuk ${fasiliti} (${venue}) telah dibatalkan.`,
      dibatalkanPemohonTajuk: "Tempahan anda dibatalkan",
      dibatalkanPemohonBadan: (fasiliti: string) => `Tempahan ${fasiliti} anda telah dibatalkan oleh pentadbir.`,
      eskalasiTajuk: "SLA kelulusan tertunggak — tindakan diperlukan",
      eskalasiBadan: (fasiliti: string, venue: string, peringkat: string, hariTertunggak: number) =>
        `Tempahan ${fasiliti} (${venue}) tertunggak kelulusan peringkat ${peringkat} selama ${hariTertunggak} hari melebihi SLA. Sila semak dan bertindak.`,
    },
    corakUlangan: {
      mingguan: "Mingguan",
      bulanan: "Bulanan",
    },
    jenisTempahan: {
      dalaman_kemas: "Dalaman KEMAS (HQ/Negeri/Daerah)",
      umum: "Tempahan Umum",
    },
    status: {
      menunggu_kelulusan_pic: "Menunggu Kelulusan PIC",
      menunggu_kelulusan_hq: "Menunggu Kelulusan HQ",
      diluluskan: "Diluluskan",
      ditolak: "Ditolak",
      dibatalkan: "Dibatalkan",
      perlu_pindah: "Perlu Dipindah",
    },
    kalendar: {
      tajuk: "Kalendar Tempahan",
      lihatKalendar: "Kalendar",
      view: {
        harian: "Harian",
        mingguan: "Mingguan",
        bulanan: "Bulanan",
      },
      sebelum: "◀ Sebelum",
      seterusnya: "Seterusnya ▶",
      hariIni: "Hari Ini",
      tiadaTempahan: "Tiada tempahan.",
      fasilitiLain: "Fasiliti Lain (premis sama)",
      // Isnin mula minggu — padan startOfWeek() calendar-rules.ts.
      hariSingkatan: ["Isnin", "Selasa", "Rabu", "Khamis", "Jumaat", "Sabtu", "Ahad"],
    },
  },
  latihan: {
    kursus: "Kursus",
    pendaftaran: "Pendaftaran",
    kehadiran: "Kehadiran",
    penceramah: "Penceramah",
    kuiz: "Kuiz",
    portal: "Portal Saya",
  },
  apex: {
    tajuk: "Sistem Pengurusan BLPP KEMAS",
    keterangan:
      "Pilih sistem untuk diteruskan.",
    butangAset: "Aset & Premis",
    butangLatihan: "Latihan",
  },
  ralat: {
    umum: "Ralat berlaku. Sila cuba semula.",
    tiadaAkses: "Anda tiada akses ke halaman ini.",
  },
} as const;
