// Semua string UI Bahasa Melayu — TIADA string hardcoded dalam component.
// Rujuk PRD v2.0 Seksyen 17 (AI coding rules) #7.

export const ms = {
  sistem: {
    nama: "Sistem Pengurusan BLPP KEMAS",
    namaPendek: "xBLPP",
  },
  nav: {
    aset: "Aset & Premis",
    latihan: "Latihan",
    admin: "Pentadbiran",
  },
  auth: {
    login: "Log Masuk",
    labelId: "E-mel",
    labelKataLaluan: "Kata Laluan",
    labelKataLaluanBaharu: "Kata Laluan Baharu",
    labelSahkanKataLaluan: "Sahkan Kata Laluan Baharu",
    lupaKataLaluan: "Lupa Kata Laluan?",
    resetKataLaluan: "Set Semula Kata Laluan",
    resetKataLaluanKeterangan:
      "Kata laluan anda perlu ditukar sebelum meneruskan.",
    resetKataLaluanButang: "Kemaskini Kata Laluan",
    resetKataLaluanBerjaya: "Kata laluan berjaya dikemaskini.",
    sedangLog: "Sedang log masuk...",
    ralat: {
      invalid_credentials: "E-mel atau kata laluan salah.",
      locked: "Akaun dikunci sementara akibat terlalu banyak percubaan gagal. Sila cuba semula selepas 15 minit.",
      inactive: "Akaun anda tidak aktif. Hubungi admin.",
      kataLaluanSemasaSalah: "Kata laluan semasa salah.",
      kataLaluanTidakSepadan: "Kata laluan baharu tidak sepadan.",
      kataLaluanTerlaluPendek: "Kata laluan mesti sekurang-kurangnya 10 aksara.",
    },
  },
  aset: {
    premis: "Premis",
    tempahan: "Tempahan",
    penyelenggaraan: "Penyelenggaraan",
    tambahPremis: "Tambah Premis",
    editPremis: "Kemaskini Premis",
    tambahFasiliti: "Tambah Fasiliti",
    editFasiliti: "Kemaskini Fasiliti",
    senaraiFasiliti: "Fasiliti",
    labelNama: "Nama",
    labelJenis: "Jenis",
    labelAlamat: "Alamat",
    labelNegeri: "Negeri",
    labelDaerah: "Daerah",
    labelGoogleMaps: "Pautan Google Maps",
    labelPic: "PIC Premis",
    labelStatus: "Status",
    labelKapasiti: "Kapasiti",
    picTiadaDipilih: "— Tiada —",
    simpan: "Simpan",
    kemaskini: "Kemaskini",
    berjayaDicipta: "Berjaya dicipta.",
    berjayaDikemaskini: "Berjaya dikemaskini.",
    jenisVenue: {
      akademi: "Akademi Latihan KEMAS",
      ilk: "Institut Latihan KEMAS",
      plk: "Pusat Latihan KEMAS",
      pkm: "Pusat Kegiatan Masyarakat",
    },
    statusVenue: {
      aktif: "Aktif",
      tutup: "Tutup",
    },
    jenisFasiliti: {
      dewan: "Dewan",
      bilik_seminar: "Bilik Seminar",
      makmal: "Makmal",
      asrama: "Asrama",
      lain: "Lain-lain",
    },
    statusFasiliti: {
      aktif: "Aktif",
      maintenance: "Penyelenggaraan",
      tutup: "Tutup",
    },
  },
  tempahan: {
    tajuk: "Tempahan",
    tempahBaharu: "Tempah Fasiliti",
    labelJenisTempahan: "Jenis Tempahan",
    labelFasiliti: "Fasiliti",
    labelTujuan: "Tujuan",
    labelAnggaranPeserta: "Anggaran Bilangan Peserta",
    labelMasaMula: "Masa Mula",
    labelMasaTamat: "Masa Tamat",
    labelStatus: "Status",
    maklumatPenyewa: "Maklumat Penyewa",
    labelPenyewaNama: "Nama Penyewa",
    labelPenyewaOrganisasi: "Organisasi",
    labelPenyewaTelefon: "Telefon Penyewa",
    labelPenyewaEmel: "E-mel Penyewa",
    notaKadarSewaan: "Kadar sewaan akan ditetapkan kemudian — belum berkuat kuasa buat masa ini.",
    simpan: "Hantar Tempahan",
    tiadaTempahan: "Tiada tempahan lagi.",
    amaranKelulusanNegeri:
      "Tempahan lebih 12 bulan ke hadapan memerlukan perhatian tambahan semasa semakan HQ.",
    amaranDwiKelulusan: "Setiap tempahan perlu kelulusan PIC premis, kemudian kelulusan HQ.",
    tempahBerulang: "Tempah Berulang",
    labelCorakUlangan: "Corak Ulangan",
    labelBilanganUlangan: "Bilangan Ulangan",
    notaKejadianPertama: "Tarikh/masa di atas ialah kejadian PERTAMA — kejadian seterusnya dijana automatik.",
    simpanBerulang: "Hantar Siri Tempahan",
    ringkasanBerulang: "Ringkasan Siri Tempahan",
    ringkasanBerjaya: (created: number, total: number) => `${created} daripada ${total} kejadian berjaya ditempah.`,
    ringkasanGagalTajuk: "Kejadian yang gagal:",
    lihatSenarai: "Lihat Senarai Tempahan",
    tempahLagiSatu: "Tempah Lagi",
    lulus: "Lulus",
    tolak: "Tolak",
    labelSebabTolak: "Sebab Penolakan",
    hantarPenolakan: "Hantar Penolakan",
    labelPicLulus: "Kelulusan PIC",
    labelHqLulus: "Kelulusan HQ",
    labelPemohon: "Pemohon",
    belumBertindak: "Belum bertindak",
    ditolakOleh: "Ditolak Oleh",
    slaDeadline: "Tarikh Akhir SLA",
    tindakanPic: "Tindakan Kelulusan (Peringkat PIC)",
    tindakanHq: "Tindakan Kelulusan (Peringkat HQ)",
    ralat: {
      tarikhLampau: "Tempahan tarikh lampau tidak dibenarkan.",
      konflik: "Fasiliti ini sudah ditempah pada masa yang bertindih. Sila pilih masa/fasiliti lain.",
      statusBukanMenunggu: "Tempahan ini sudah diproses (bukan lagi menunggu kelulusan).",
      sebabTolakWajib: "Sebab penolakan wajib diisi.",
    },
    notifikasi: {
      picBaharuTajuk: "Tempahan baharu menunggu kelulusan anda",
      picBaharuBadan: (fasiliti: string, venue: string) =>
        `Tempahan baharu untuk ${fasiliti} (${venue}) menunggu kelulusan PIC anda.`,
      picLulusTajuk: "Tempahan anda diluluskan PIC",
      picLulusBadan: (fasiliti: string) => `Tempahan ${fasiliti} anda diluluskan PIC, kini menunggu kelulusan HQ.`,
      hqMenungguTajuk: "Tempahan menunggu kelulusan HQ",
      hqMenungguBadan: (fasiliti: string, venue: string) =>
        `Tempahan ${fasiliti} (${venue}) telah diluluskan PIC, menunggu kelulusan HQ.`,
      diluluskanTajuk: "Tempahan diluluskan penuh",
      diluluskanBadan: (fasiliti: string) => `Tempahan ${fasiliti} telah diluluskan sepenuhnya (PIC + HQ).`,
      ditolakTajuk: "Tempahan ditolak",
      ditolakBadan: (fasiliti: string, sebab: string) => `Tempahan ${fasiliti} ditolak. Sebab: ${sebab}`,
    },
    corakUlangan: {
      mingguan: "Mingguan",
      bulanan: "Bulanan",
    },
    jenisTempahan: {
      dalaman_kemas: "Dalaman KEMAS (HQ/Negeri/Daerah)",
      umum: "Tempahan Umum",
    },
    status: {
      menunggu_kelulusan_pic: "Menunggu Kelulusan PIC",
      menunggu_kelulusan_hq: "Menunggu Kelulusan HQ",
      diluluskan: "Diluluskan",
      ditolak: "Ditolak",
      dibatalkan: "Dibatalkan",
      perlu_pindah: "Perlu Dipindah",
    },
  },
  latihan: {
    kursus: "Kursus",
    pendaftaran: "Pendaftaran",
    kehadiran: "Kehadiran",
    penceramah: "Penceramah",
    kuiz: "Kuiz",
    portal: "Portal Saya",
  },
  ralat: {
    umum: "Ralat berlaku. Sila cuba semula.",
    tiadaAkses: "Anda tiada akses ke halaman ini.",
  },
} as const;
